name: validate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Link Validator
      id: urlsup
      uses: simeg/urlsup@v1
      with:
        files: "README.md"
